CREATE TABLE `sg_order` (
 `id` int(11) NOT NULL AUTO_INCREMENT,
 `SN` bigint(16) DEFAULT NULL COMMENT '订单号',
 `title` varchar(255) DEFAULT NULL COMMENT '标题',
 `content_id` int(11) DEFAULT NULL COMMENT '内容id',
 `type` tinyint(2) unsigned NOT NULL DEFAULT '0' COMMENT '1法律 2财税 3普通',
 `price` int(11) DEFAULT NULL COMMENT '订单价格',
 `attribute` varchar(255) DEFAULT NULL COMMENT '订单扩展属性',
 `status` tinyint(2) DEFAULT NULL COMMENT '状态：0未完成1待审核2已完成3已取消4审核失败',
 `server_id` int(11) DEFAULT NULL COMMENT '服务人员id',
 `channel_id` int(11) DEFAULT NULL COMMENT '订单类型id（频道id）',
 `uid` int(11) DEFAULT NULL COMMENT '用户id',
 `site_id` int(11) DEFAULT NULL COMMENT '站点id',
 `add_time` int(11) DEFAULT NULL COMMENT '下单时间',
 `audit_time` int(11) DEFAULT NULL,
 `audit_fail_time` int(11) DEFAULT NULL,
 `pay_time` int(11) DEFAULT NULL,
 `complete_time` int(11) DEFAULT NULL,
 `cancel_time` int(11) DEFAULT NULL,
 `invalid_time` int(11) DEFAULT NULL,
 `remark` varchar(255) DEFAULT NULL,
 `have_bill` int(11) DEFAULT NULL COMMENT '0表示没有发送账单1有未付款的账单2有已付款的账单',
 PRIMARY KEY (`id`),
 UNIQUE KEY `SN` (`SN`)
) ENGINE=MyISAM AUTO_INCREMENT=29 DEFAULT CHARSET=utf8
